(function(g){var window=this;var sya=function(a,b,c,d){var e=b.fc();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.nd(c,d?d:"mqdefault.jpg");var k=b instanceof g.mN?g.HV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.GP(f).type;var m=b instanceof g.mN?b.wa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Jn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.IP&&(c.playlist_length=b.getLength());a.update(c)},v5=function(a,b){g.iV.call(this,{H:"div",
ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.created=!1},w5=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.T("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={role:"button",href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",V:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",V:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",V:c,K:[{H:"svg",V:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},
K:[{H:"circle",M:"ytp-svg-autoplay-circle",V:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",V:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",V:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]}]};
g.Y.call(this,b);this.B=null;b=this.sa["ytp-upnext-cancel"];this.B=new g.Y({H:"button",ba:["ytp-upnext-cancel-button","ytp-button"],V:{tabindex:"0","aria-label":g.T("YTP_AUTOPLAY_CANCEL")},K:[g.T("YTP_CANCEL")]});g.M(this,this.B);this.B.U("click",this.mO,this);this.B.Da(b);this.o=a;this.J=this.sa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Yt(this.Ym,5E3,this);g.M(this,this.G);this.I=0;this.P(this.sa["ytp-upnext-autoplay-icon"],"click",this.uQ);this.JA();this.P(a,"autonavvisibility",
this.JA);this.P(a,"mdxnowautoplaying",this.JP);this.P(a,"mdxautoplaycanceled",this.KP);this.P(a,"mdxautoplayupnext",this.cD);3==this.o.Qa()&&(a=(a=g.jU(g.eU(this.o)))?a.BH():null)&&this.cD(a)},tya=function(a,b){a.C=b;
sya(a,b,g.X(a.o),"hqdefault.jpg")},x5=function(a,b){a.A||(g.RF("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=g.cG(),a.A=new g.Yt((0,g.z)(a.Xp,a,b),25),a.Xp(b));
g.qq(a.element,"ytp-upnext-autoplay-paused")},z5=function(a){y5(a);
a.I=g.cG();a.Xp();g.R(a.element,"ytp-upnext-autoplay-paused")},y5=function(a){a.A&&(a.A.dispose(),a.A=null)},A5=function(a,b){b=void 0===b?!1:b;
var c=g.X(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.tU(a.o,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.fc(),a.Ym(),a.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.nd(c)}),a.F=a.P(a.D,"click",a.kQ),a.G.start())}y5(a);a.o.Hj(!1,b)},uya=function(a){v5.call(this,a,"subscribecard-endscreen");
var b=a.fa();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",V:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Da(this.element);this.B=new g.E_(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.Ql,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Da(this.A.sa["html5-subscribe-button-container"]);this.hide()},
B5=function(a){var b=g.X(a),c=g.kJ||g.$e?{style:"will-change: opacity"}:void 0,d=b.B&&!b.F,e=["ytp-videowall-still"];
b.experiments.g("web_player_video_wall_show_text")&&b.isMobile&&e.push("ytp-videowall-show-text");g.Y.call(this,{H:"a",ba:e,V:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",V:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",V:c,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.T("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ba:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=d;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.D);g.X(a).aa&&(a=a.app.ca,b=this.element,g.kb(a.g,b),g.qb(a.g,b),c=String(a.G++),b.setAttribute("data-visual-id",c),g.Ve(this,(0,g.z)(a.F,a,b)))},C5=function(a){v5.call(this,a,"videowall-endscreen");
this.R=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.O=!1;this.F=new g.yF(this);g.M(this,this.F);this.L=new g.Yt(g.Da(g.R,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ba:["ytp-button","ytp-endscreen-previous"],V:{"aria-label":g.T("YTP_PREVIOUS")},K:[g.mV()]});g.M(this,b);b.Da(this.element);b.U("click",this.RK,this);this.N=new g.OU({H:"div",M:"ytp-endscreen-content"});g.M(this,this.N);this.N.Da(this.element);b=new g.Y({H:"button",ba:["ytp-button","ytp-endscreen-next"],
V:{"aria-label":g.T("YTP_NEXT")},K:[g.nV()]});g.M(this,b);b.Da(this.element);b.U("click",this.QK,this);this.A=new w5(a);g.M(this,this.A);g.FU(this.o,this.A.element,4);this.hide()},D5=function(a){return g.GU(a.o)&&a.bq()&&!a.I},vya=function(a){return(0,g.H)(a.suggestions,function(a){return g.GY(a)})},E5=function(a){var b=a.Is();
b!=a.O&&(a.O=b,a.o.T("autonavvisibility"))},F5=function(a){g.LU.call(this,a);
g.EG({YTP_AUTOPLAY_CANCEL:"Cancel autoplay",YTP_AUTOPLAY_NEXT:"Play next video",YTP_AUTOPLAY_PAUSED_3:"Autoplay is paused",YTP_PLAYLIST_UP_NEXT:"Up Next",YTP_WATCH_VIDEO_OR_PLAYLIST:"Watch $TITLE"});this.o=null;this.A=new g.yF(this);g.M(this,this.A);this.B=g.X(a);wya(a)?this.o=new C5(this.g):this.B.la?this.o=new uya(this.g):this.o=new v5(this.g);g.M(this,this.o);g.FU(this.g,this.o.element,4);this.VB();this.A.P(a,"videodatachange",this.VB,this);this.A.P(a,"crn_endscreen",this.sK,this);this.A.P(a,"crx_endscreen",
this.tK,this)},wya=function(a){a=g.X(a);
return a.Id&&!a.la};
g.p(v5,g.iV);v5.prototype.create=function(){this.created=!0};
v5.prototype.destroy=function(){this.created=!1};
v5.prototype.bq=function(){return!1};
v5.prototype.Is=function(){return!1};g.p(w5,g.Y);g.h=w5.prototype;g.h.Ym=function(){this.D&&(this.G.stop(),this.Ea(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.JA=function(){g.VU(this,g.fU(this.o))};
g.h.kQ=function(){window.focus();this.Ym()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.Xp=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min(g.cG()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Qa()?A5(this,!0):this.A&&this.A.start()};
g.h.uQ=function(a){!g.Od(this.B.element,g.oF(a))&&g.tY(a,this.o)&&A5(this)};
g.h.mO=function(){g.hU(this.o,!0)};
g.h.JP=function(a){this.o.Qa();this.show();x5(this,a)};
g.h.cD=function(a){this.o.Qa();this.C&&this.C.fc().videoId==a.fc().videoId||tya(this,a)};
g.h.KP=function(){this.o.Qa();y5(this);this.hide()};
g.h.W=function(){y5(this);this.Ym();g.Y.prototype.W.call(this)};g.p(uya,v5);g.p(B5,g.Y);B5.prototype.Xj=function(){var a=this.A.fc().videoId,b=this.A.getPlaylistId();g.o0(this.o.app,a,this.A.Ud,b,void 0,void 0,void 0)};
B5.prototype.C=function(a){g.JU(this.o,this.element);g.tY(a,this.o,this.B,this.A.Ud||void 0)&&this.Xj()};
B5.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.tF(a)||(this.Xj(),g.sF(a))}};g.p(C5,v5);g.h=C5.prototype;g.h.create=function(){v5.prototype.create.call(this);var a=this.o.fa();a&&(this.C=vya(a),this.D=a);this.xh();this.F.P(this.o,"appresize",this.xh);this.F.P(this.o,"videodatachange",this.SK);this.F.P(this.o,"autonavchange",this.pz);this.F.P(this.o,"autonavcancel",this.PK);this.F.P(this.element,"transitionend",this.AR)};
g.h.destroy=function(){g.AF(this.F);g.Xe(this.B);this.B=[];this.C=null;v5.prototype.destroy.call(this);g.qq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.bq=function(){return 1!=this.D.autonavState};
g.h.show=function(){v5.prototype.show.call(this);g.qq(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.$t(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.hU(this.o,!1);var a=D5(this);g.GU(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.tU(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.bq()?"enabled":"disabled"});a?(E5(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Ai()?A5(this.A,!0):x5(this.A):3==this.D.autonavState&&
z5(this.A)):(g.hU(this.o,!0),E5(this))};
g.h.hide=function(){v5.prototype.hide.call(this);z5(this.A);E5(this)};
g.h.AR=function(a){g.oF(a)==this.element&&this.xh()};
g.h.xh=function(){if(this.C&&this.C.length){g.R(this.element,"ytp-endscreen-paginate");var a=g.Hh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(d<f||e<k);){var q=d/2,r=e/2,t=d<=f-2&&n>=r*m,B=e<=k-2&&n>=q*m;if((q+1)/r*c/b>b/(q/(r+1)*c)&&B)n-=q*m,e+=2;else if(t)n-=r*m,d+=2;else if(B)n-=q*m,e+=2;else break}c=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=d)&&(c=!0);m=96*
d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.$c(a.width/m||1,1,1.21);n*=g.$c(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Gh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});tya(this.A,this.C[0]);g.S(this.element,"ytp-endscreen-takeover",D5(this));E5(this);m+=4;n+=4;for(f=b=0;f<d;f++)for(k=0;k<e;k++)if(q=b,r=0,c&&f>=d-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.ad(q+this.G,l),0!=
r){t=this.B[b];t||(t=new B5(this.o),this.B[b]=t,a.appendChild(t.element));B=Math.floor(n*k/e);var E=Math.floor(m*f/d),I=Math.floor(n*(k+r)/e)-B-4,W=Math.floor(m*(f+r)/d)-E-4;g.vh(t.element,E,B);g.Gh(t.element,W,I);g.oh(t.element,"transitionDelay",(k+f)/20+"s");g.S(t.element,"ytp-videowall-still-mini",1==r);g.S(t.element,"ytp-videowall-still-large",2<r);r=t;q=this.C[q];r.A=q;sya(r,q,g.X(r.o),g.oq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");t=q.Ud;q=r.o;g.X(q).aa&&(q=q.app.ca,
r=r.element,t=t&&t.itct,B=r.getAttribute("data-visual-id"),g.kb(q.g,r),g.HU(q,"onLogServerVeCreated",{id:B,tracking_params:t}));b++}g.S(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Hd(e.element),g.We(e);this.B.length=b}};
g.h.SK=function(){var a=this.o.fa();this.D!=a&&(this.G=0,this.C=vya(a),this.D=a,this.xh())};
g.h.QK=function(){this.G+=this.B.length;this.xh()};
g.h.RK=function(){this.G-=this.B.length;this.xh()};
g.h.AJ=function(){return!!this.A.A};
g.h.pz=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,y5(this.A),this.g&&this.xh()):(this.J=!0,this.g&&D5(this)&&(2==a?x5(this.A):3==a&&z5(this.A)))};
g.h.PK=function(a){if(a){for(a=0;a<this.B.length;a++)g.KU(this.R,this.B[a].element,!0);this.pz(1)}else this.I=null,this.J=!1;this.xh()};
g.h.Is=function(){return this.g&&D5(this)};g.p(F5,g.LU);g.h=F5.prototype;g.h.kz=function(){var a=this.g.fa(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!wya(this.g)||b;a=g.FN(a,"ypc_module");var c=g.p0(this.g.app);return b&&!a&&!c};
g.h.jz=function(){return this.o.Is()};
g.h.xJ=function(){return this.jz()?this.o.AJ():!1};
g.h.W=function(){g.BU(this.g,"endscreen");g.LU.prototype.W.call(this)};
g.h.load=function(){g.LU.prototype.load.call(this);this.o.show();g.X(this.g).la&&.01>Math.random()&&g.tU(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.LU.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.sK=function(a){this.kz()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.tK=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.VB=function(){g.BU(this.g,"endscreen");var a=Math.max(1E3*(this.g.fa().lengthSeconds-10),0);a=new g.CP(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.CP(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.yU(this.g,[a,b])};g.hY.endscreen=F5;})(_yt_player);
